apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: prometheus-example-rules
  namespace: bgd
spec:
  groups:
  - name: GitOpsOperatorArgoCD
    rules:
    - alert: ArgoCDSyncAlert
      expr: sample
